GET http://localhost:3333/health

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "email": "dunha@gmail.com",
  "passwordHash": "açldkjfalkjdflçakjsdf",
  "fullName": "Dunha Dunha",
  "profileImageUrl": ""
}

###
PUT http://localhost:3333/users/cm7z54t4d00002l6k4h2bvnw6
Content-Type: application/json

{
  "email": "dunha2@gmail.com",
  "fullName": "Dunha Dunha Dunha",
  "profileImageUrl": ""
}

###
GET http://localhost:3333/users/cm7yj4qnv000008gv6mueoiea