GET http://localhost:3333/health

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "email": "dunha@gmail.com",
  "passwordHash": "açldkjfalkjdflçakjsdf",
  "fullName": "Dunha Dunha",
  "profileImageUrl": ""
}