import { MatchStage, MatchStatus, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface MatchData {
  homeTeam: string;
  awayTeam: string;
  datetime: string;
  stage: string;
  group: string;
  stadium: string;
  homeScore: number;
  awayScore: number;
}

export async function createGroupMatches(tournamentId: number, teamMap: { [key: string]: number }) {
  const groupMatches: MatchData[] = [
    // Group A
    {
      homeTeam: 'Qatar',
      awayTeam: 'Ecuador',
      datetime: '2022-11-20T16:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Al Bayt Stadium',
      homeScore: 0,
      awayScore: 2,
    },
    {
      homeTeam: 'Senegal',
      awayTeam: 'Netherlands',
      datetime: '2022-11-21T16:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Al Thumama Stadium',
      homeScore: 0,
      awayScore: 2,
    },
    {
      homeTeam: 'Qatar',
      awayTeam: 'Senegal',
      datetime: '2022-11-25T13:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Al Thumama Stadium',
      homeScore: 1,
      awayScore: 3,
    },
    {
      homeTeam: 'Netherlands',
      awayTeam: 'Ecuador',
      datetime: '2022-11-25T16:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Khalifa International Stadium',
      homeScore: 1,
      awayScore: 1,
    },
    {
      homeTeam: 'Netherlands',
      awayTeam: 'Qatar',
      datetime: '2022-11-29T15:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Al Bayt Stadium',
      homeScore: 2,
      awayScore: 0,
    },
    {
      homeTeam: 'Ecuador',
      awayTeam: 'Senegal',
      datetime: '2022-11-29T15:00:00Z',
      stage: 'Group A',
      group: 'A',
      stadium: 'Khalifa International Stadium',
      homeScore: 1,
      awayScore: 2,
    },

    // Group B
    {
      homeTeam: 'England',
      awayTeam: 'Iran',
      datetime: '2022-11-21T13:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Khalifa International Stadium',
      homeScore: 6,
      awayScore: 2,
    },
    {
      homeTeam: 'USA',
      awayTeam: 'Wales',
      datetime: '2022-11-21T19:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 1,
      awayScore: 1,
    },
    {
      homeTeam: 'Wales',
      awayTeam: 'Iran',
      datetime: '2022-11-25T10:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 0,
      awayScore: 2,
    },
    {
      homeTeam: 'England',
      awayTeam: 'USA',
      datetime: '2022-11-25T19:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Al Bayt Stadium',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'Wales',
      awayTeam: 'England',
      datetime: '2022-11-29T19:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 0,
      awayScore: 3,
    },
    {
      homeTeam: 'Iran',
      awayTeam: 'USA',
      datetime: '2022-11-29T19:00:00Z',
      stage: 'Group B',
      group: 'B',
      stadium: 'Al Thumama Stadium',
      homeScore: 0,
      awayScore: 1,
    },

    // Group C
    {
      homeTeam: 'Argentina',
      awayTeam: 'Saudi Arabia',
      datetime: '2022-11-22T10:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Lusail Stadium',
      homeScore: 1,
      awayScore: 2,
    },
    {
      homeTeam: 'Mexico',
      awayTeam: 'Poland',
      datetime: '2022-11-22T16:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Stadium 974',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'Poland',
      awayTeam: 'Saudi Arabia',
      datetime: '2022-11-26T13:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Education City Stadium',
      homeScore: 2,
      awayScore: 0,
    },
    {
      homeTeam: 'Argentina',
      awayTeam: 'Mexico',
      datetime: '2022-11-26T19:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Lusail Stadium',
      homeScore: 2,
      awayScore: 0,
    },
    {
      homeTeam: 'Poland',
      awayTeam: 'Argentina',
      datetime: '2022-11-30T19:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Stadium 974',
      homeScore: 0,
      awayScore: 2,
    },
    {
      homeTeam: 'Saudi Arabia',
      awayTeam: 'Mexico',
      datetime: '2022-11-30T19:00:00Z',
      stage: 'Group C',
      group: 'C',
      stadium: 'Lusail Stadium',
      homeScore: 1,
      awayScore: 2,
    },

    // Group D
    {
      homeTeam: 'Denmark',
      awayTeam: 'Tunisia',
      datetime: '2022-11-22T13:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Education City Stadium',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'France',
      awayTeam: 'Australia',
      datetime: '2022-11-22T19:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Al Janoub Stadium',
      homeScore: 4,
      awayScore: 1,
    },
    {
      homeTeam: 'Tunisia',
      awayTeam: 'Australia',
      datetime: '2022-11-26T10:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Al Janoub Stadium',
      homeScore: 0,
      awayScore: 1,
    },
    {
      homeTeam: 'France',
      awayTeam: 'Denmark',
      datetime: '2022-11-26T16:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Stadium 974',
      homeScore: 2,
      awayScore: 1,
    },
    {
      homeTeam: 'Tunisia',
      awayTeam: 'France',
      datetime: '2022-11-30T15:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Education City Stadium',
      homeScore: 1,
      awayScore: 0,
    },
    {
      homeTeam: 'Australia',
      awayTeam: 'Denmark',
      datetime: '2022-11-30T15:00:00Z',
      stage: 'Group D',
      group: 'D',
      stadium: 'Al Janoub Stadium',
      homeScore: 1,
      awayScore: 0,
    },
    // Group E
    {
      homeTeam: 'Germany',
      awayTeam: 'Japan',
      datetime: '2022-11-23T13:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Khalifa International Stadium',
      homeScore: 1,
      awayScore: 2,
    },
    {
      homeTeam: 'Spain',
      awayTeam: 'Costa Rica',
      datetime: '2022-11-23T16:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Al Thumama Stadium',
      homeScore: 7,
      awayScore: 0,
    },
    {
      homeTeam: 'Japan',
      awayTeam: 'Costa Rica',
      datetime: '2022-11-27T10:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 0,
      awayScore: 1,
    },
    {
      homeTeam: 'Spain',
      awayTeam: 'Germany',
      datetime: '2022-11-27T19:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Al Bayt Stadium',
      homeScore: 1,
      awayScore: 1,
    },
    {
      homeTeam: 'Japan',
      awayTeam: 'Spain',
      datetime: '2022-12-01T19:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Khalifa International Stadium',
      homeScore: 2,
      awayScore: 1,
    },
    {
      homeTeam: 'Costa Rica',
      awayTeam: 'Germany',
      datetime: '2022-12-01T19:00:00Z',
      stage: 'Group E',
      group: 'E',
      stadium: 'Al Bayt Stadium',
      homeScore: 2,
      awayScore: 4,
    },

    // Group F
    {
      homeTeam: 'Morocco',
      awayTeam: 'Croatia',
      datetime: '2022-11-23T10:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Al Bayt Stadium',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'Belgium',
      awayTeam: 'Canada',
      datetime: '2022-11-23T19:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 1,
      awayScore: 0,
    },
    {
      homeTeam: 'Belgium',
      awayTeam: 'Morocco',
      datetime: '2022-11-27T13:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Al Thumama Stadium',
      homeScore: 0,
      awayScore: 2,
    },
    {
      homeTeam: 'Croatia',
      awayTeam: 'Canada',
      datetime: '2022-11-27T16:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Khalifa International Stadium',
      homeScore: 4,
      awayScore: 1,
    },
    {
      homeTeam: 'Croatia',
      awayTeam: 'Belgium',
      datetime: '2022-12-01T15:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Ahmad Bin Ali Stadium',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'Canada',
      awayTeam: 'Morocco',
      datetime: '2022-12-01T15:00:00Z',
      stage: 'Group F',
      group: 'F',
      stadium: 'Al Thumama Stadium',
      homeScore: 1,
      awayScore: 2,
    },

    // Group G
    {
      homeTeam: 'Switzerland',
      awayTeam: 'Cameroon',
      datetime: '2022-11-24T10:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Al Janoub Stadium',
      homeScore: 1,
      awayScore: 0,
    },
    {
      homeTeam: 'Brazil',
      awayTeam: 'Serbia',
      datetime: '2022-11-24T19:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Lusail Stadium',
      homeScore: 2,
      awayScore: 0,
    },
    {
      homeTeam: 'Cameroon',
      awayTeam: 'Serbia',
      datetime: '2022-11-28T10:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Al Janoub Stadium',
      homeScore: 3,
      awayScore: 3,
    },
    {
      homeTeam: 'Brazil',
      awayTeam: 'Switzerland',
      datetime: '2022-11-28T16:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Stadium 974',
      homeScore: 1,
      awayScore: 0,
    },
    {
      homeTeam: 'Cameroon',
      awayTeam: 'Brazil',
      datetime: '2022-12-02T19:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Lusail Stadium',
      homeScore: 1,
      awayScore: 0,
    },
    {
      homeTeam: 'Serbia',
      awayTeam: 'Switzerland',
      datetime: '2022-12-02T19:00:00Z',
      stage: 'Group G',
      group: 'G',
      stadium: 'Stadium 974',
      homeScore: 2,
      awayScore: 3,
    },
    // Group H
    {
      homeTeam: 'Uruguay',
      awayTeam: 'South Korea',
      datetime: '2022-11-24T13:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Education City Stadium',
      homeScore: 0,
      awayScore: 0,
    },
    {
      homeTeam: 'Portugal',
      awayTeam: 'Ghana',
      datetime: '2022-11-24T16:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Stadium 974',
      homeScore: 3,
      awayScore: 2,
    },
    {
      homeTeam: 'South Korea',
      awayTeam: 'Ghana',
      datetime: '2022-11-28T13:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Education City Stadium',
      homeScore: 2,
      awayScore: 3,
    },
    {
      homeTeam: 'Portugal',
      awayTeam: 'Uruguay',
      datetime: '2022-11-28T19:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Lusail Stadium',
      homeScore: 2,
      awayScore: 0,
    },
    {
      homeTeam: 'South Korea',
      awayTeam: 'Portugal',
      datetime: '2022-12-02T15:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Education City Stadium',
      homeScore: 2,
      awayScore: 1,
    },
    {
      homeTeam: 'Ghana',
      awayTeam: 'Uruguay',
      datetime: '2022-12-02T15:00:00Z',
      stage: 'Group H',
      group: 'H',
      stadium: 'Al Janoub Stadium',
      homeScore: 0,
      awayScore: 2,
    },
  ];

  // Create all group matches
  for (const match of groupMatches) {
    await prisma.match.create({
      data: {
        tournamentId: tournamentId,
        homeTeamId: teamMap[match.homeTeam],
        awayTeamId: teamMap[match.awayTeam],
        matchDatetime: new Date(match.datetime),
        stadium: match.stadium,
        stage: MatchStage.GROUP,
        group: match.group,
        homeTeamScore: match.homeScore,
        awayTeamScore: match.awayScore,
        matchStatus: MatchStatus.COMPLETED,
      },
    });
    console.log(`Created match: ${match.homeTeam} vs ${match.awayTeam}`);
  }
}
