name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

concurrency:
  group: deploy-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  deploy:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Trigger Render deploy hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "${RENDER_DEPLOY_HOOK:-}" ]; then
            echo "Render deploy hook secret is not set" >&2
            exit 1
          fi

          echo "Triggering Render deploy hook"
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
